name: Android CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x android/pixhawk-gcs-lite/gradlew

    - name: Build debug APK
      run: |
        cd android/pixhawk-gcs-lite
        ./gradlew assembleDebug --stacktrace

    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: pixhawk-gcs-lite-debug.apk
        path: android/pixhawk-gcs-lite/app/build/outputs/apk/debug/*.apk

    - name: Create project archive
      run: |
        cd android
        zip -r pixhawk-gcs-lite-project.zip pixhawk-gcs-lite/ -x "pixhawk-gcs-lite/build/*" "pixhawk-gcs-lite/app/build/*" "pixhawk-gcs-lite/.gradle/*"

    - name: Upload Project Archive
      uses: actions/upload-artifact@v3
      with:
        name: pixhawk-gcs-lite-project
        path: android/pixhawk-gcs-lite-project.zip